import type { Student } from './types';

/**
 * Mock student directory used to populate the prototype.
 * These are fictional demo profiles, not real people.
 */
export const STUDENTS: Student[] = [
  {
    id: 's1',
    name: 'Aarav Mehta',
    avatarSeed: 3,
    emoji: '🚀',
    college: 'Jai Hind College',
    course: 'BMS',
    year: '2nd Year',
    bio: 'Building a campus delivery side project. Always up for a whiteboard session at the canteen.',
    interests: ['Entrepreneurship', 'Technology', 'Marketing', 'Social Impact'],
    hobbies: ['Coding side projects', 'Football', 'Podcasts'],
    skills: ['Product thinking', 'Sales', 'Social media'],
    careerInterests: ['Startups', 'Product management'],
    goals: ['Build a startup', 'Build a portfolio', 'Grow my network'],
    personality: ['Extroverted', 'Curious', 'Competitive'],
    activities: ['Startup / E-Cell events', 'Hackathons', 'Football matches'],
    lookingFor: [
      'Entrepreneurship / startup connections',
      'Find teammates',
      'Work on projects'
    ]
  },
  {
    id: 's2',
    name: 'Ishita Rao',
    avatarSeed: 7,
    emoji: '📷',
    college: 'Jai Hind College',
    course: 'BMM / Mass Media',
    year: '2nd Year',
    bio: 'Photography club member. Looking for people to do Sunday photowalks around South Bombay.',
    interests: ['Photography', 'Film & Cinema', 'Travel', 'Design'],
    hobbies: ['Photography', 'Video editing', 'Sketching'],
    skills: ['Photography', 'Video editing', 'Graphic design'],
    careerInterests: ['Media & journalism', 'Design'],
    goals: ['Build a portfolio', 'Publish my work', 'Learn a new skill'],
    personality: ['Creative', 'Ambivert', 'Empathetic'],
    activities: ['Photowalks', 'Film screenings', 'Long walks & city exploring'],
    lookingFor: [
      'Find people with similar interests',
      'Explore new hobbies',
      'Make new friends'
    ]
  },
  {
    id: 's3',
    name: 'Rohan Desai',
    avatarSeed: 1,
    emoji: '📚',
    college: 'Jai Hind College',
    course: 'BCom',
    year: '3rd Year',
    bio: 'CA foundation grind. Prefer 7am library slots. Serious about study partners, relaxed about everything else.',
    interests: ['Finance & Markets', 'Literature', 'Sports'],
    hobbies: ['Reading', 'Running', 'Chess'],
    skills: ['Accounting', 'Financial modelling', 'Research'],
    careerInterests: ['Investment banking', 'Consulting'],
    goals: ['Improve my grades', 'Crack placements', 'Land an internship'],
    personality: ['Introverted', 'Analytical', 'Organised'],
    activities: ['Library grind', 'Cafe study sessions', 'Morning runs'],
    lookingFor: ['Find a study partner', 'Networking', 'Make new friends']
  },
  {
    id: 's4',
    name: 'Sara Khan',
    avatarSeed: 10,
    emoji: '🧠',
    college: 'Jai Hind College',
    course: 'BA Psychology',
    year: '1st Year',
    bio: 'New to campus and genuinely trying to meet people. Will talk about behavioural science for hours.',
    interests: ['Psychology', 'Literature', 'Social Impact', 'Music'],
    hobbies: ['Reading', 'Singing', 'Board games'],
    skills: ['Research', 'Public speaking', 'Teaching / tutoring'],
    careerInterests: ['Academia & research', 'Social sector'],
    goals: ['Grow my network', 'Learn a new skill', 'Publish my work'],
    personality: ['Empathetic', 'Curious', 'Ambivert'],
    activities: ['Cafe study sessions', 'Volunteering', 'Open mics'],
    lookingFor: ['Make new friends', 'Find a study partner', 'Networking']
  },
  {
    id: 's5',
    name: 'Kabir Nair',
    avatarSeed: 5,
    emoji: '🎸',
    college: 'Jai Hind College',
    course: 'BSc Computer Science',
    year: '3rd Year',
    bio: 'Backend dev by day, guitarist by night. Want to jam or ship something? Both work.',
    interests: ['Technology', 'AI & Machine Learning', 'Music', 'Gaming'],
    hobbies: ['Guitar', 'Coding side projects', 'Gaming'],
    skills: ['Python', 'JavaScript', 'React', 'Data analysis'],
    careerInterests: ['Software engineering', 'Startups'],
    goals: ['Build a startup', 'Crack placements', 'Build a portfolio'],
    personality: ['Introverted', 'Analytical', 'Creative'],
    activities: ['Hackathons', 'Music jams', 'Startup / E-Cell events'],
    lookingFor: ['Find teammates', 'Work on projects', 'Explore new hobbies']
  },
  {
    id: 's6',
    name: 'Ananya Iyer',
    avatarSeed: 12,
    emoji: '🎤',
    college: 'Jai Hind College',
    course: 'BMS',
    year: '3rd Year',
    bio: 'Debate team. I organise more events than I attend. Looking for people who like a good argument.',
    interests: ['Public Speaking', 'Debate', 'Marketing', 'Sustainability'],
    hobbies: ['Writing', 'Theatre', 'Reading'],
    skills: ['Public speaking', 'Event management', 'Copywriting'],
    careerInterests: ['Consulting', 'Marketing & brand'],
    goals: ['Win a case competition', 'Organise campus events', 'Grow my network'],
    personality: ['Extroverted', 'Competitive', 'Organised'],
    activities: ['Case competitions', 'Open mics', 'Volunteering'],
    lookingFor: [
      'Find teammates',
      'Networking',
      'Find people to attend events with'
    ]
  },
  {
    id: 's7',
    name: 'Dev Sharma',
    avatarSeed: 2,
    emoji: '🏀',
    college: 'Jai Hind College',
    course: 'BAF',
    year: '2nd Year',
    bio: 'Gym at 6am, markets by 9. Looking for a training partner who actually turns up.',
    interests: ['Finance & Markets', 'Sports', 'Food'],
    hobbies: ['Gym', 'Basketball', 'Cooking'],
    skills: ['Financial modelling', 'Data analysis', 'Sales'],
    careerInterests: ['Investment banking', 'Startups'],
    goals: ['Get fitter', 'Land an internship', 'Crack placements'],
    personality: ['High energy', 'Competitive', 'Collaborative'],
    activities: ['Gym sessions', 'Morning runs', 'Football matches'],
    lookingFor: ['Make new friends', 'Find a study partner', 'Networking']
  },
  {
    id: 's8',
    name: 'Meera Joshi',
    avatarSeed: 8,
    emoji: '🌱',
    college: 'Jai Hind College',
    course: 'BA Economics',
    year: '2nd Year',
    bio: 'Climate policy nerd. Running a campus waste audit and need three more hands.',
    interests: ['Sustainability', 'Social Impact', 'Psychology', 'Literature'],
    hobbies: ['Trekking', 'Reading', 'Writing'],
    skills: ['Research', 'Copywriting', 'Event management'],
    careerInterests: ['Social sector', 'Academia & research', 'Civil services'],
    goals: ['Publish my work', 'Organise campus events', 'Build a portfolio'],
    personality: ['Calm', 'Empathetic', 'Organised'],
    activities: ['Volunteering', 'Long walks & city exploring', 'Cafe study sessions'],
    lookingFor: ['Work on projects', 'Find teammates', 'Make new friends']
  },
  {
    id: 's9',
    name: 'Vivaan Kulkarni',
    avatarSeed: 4,
    emoji: '🎬',
    college: 'Jai Hind College',
    course: 'BMM / Mass Media',
    year: '1st Year',
    bio: 'Short film in progress, editor still missing. Big on Kurosawa and bad canteen coffee.',
    interests: ['Film & Cinema', 'Music', 'Photography', 'Literature'],
    hobbies: ['Video editing', 'Photography', 'Podcasts'],
    skills: ['Video editing', 'Copywriting', 'Photography'],
    careerInterests: ['Media & journalism', 'Design'],
    goals: ['Build a portfolio', 'Learn a new skill', 'Publish my work'],
    personality: ['Creative', 'Introverted', 'Curious'],
    activities: ['Film screenings', 'Photowalks', 'Open mics'],
    lookingFor: ['Work on projects', 'Find people with similar interests', 'Find teammates']
  },
  {
    id: 's10',
    name: 'Tanya Bhatia',
    avatarSeed: 14,
    emoji: '🎨',
    college: 'Jai Hind College',
    course: 'BDes',
    year: '2nd Year',
    bio: 'Interface designer. I will redesign your slide deck unprompted. Sorry in advance.',
    interests: ['Design', 'Technology', 'Fashion', 'Entrepreneurship'],
    hobbies: ['Sketching', 'Coding side projects', 'Dance'],
    skills: ['UI/UX design', 'Graphic design', 'Product thinking'],
    careerInterests: ['Design', 'Startups', 'Product management'],
    goals: ['Build a portfolio', 'Build a startup', 'Land an internship'],
    personality: ['Creative', 'Collaborative', 'Curious'],
    activities: ['Hackathons', 'Startup / E-Cell events', 'Photowalks'],
    lookingFor: [
      'Find teammates',
      'Work on projects',
      'Entrepreneurship / startup connections'
    ],
    premium: true
  },
  {
    id: 's11',
    name: 'Arjun Pillai',
    avatarSeed: 6,
    emoji: '⚽',
    college: 'Jai Hind College',
    course: 'BCom',
    year: '1st Year',
    bio: 'Played district level football. Now mostly looking for a 5-a-side team and decent notes.',
    interests: ['Sports', 'Finance & Markets', 'Gaming', 'Food'],
    hobbies: ['Football', 'Gym', 'Gaming'],
    skills: ['Sales', 'Teaching / tutoring', 'Social media'],
    careerInterests: ['Startups', 'Marketing & brand'],
    goals: ['Get fitter', 'Improve my grades', 'Grow my network'],
    personality: ['Extroverted', 'High energy', 'Collaborative'],
    activities: ['Football matches', 'Gym sessions', 'Cafe study sessions'],
    lookingFor: [
      'Make new friends',
      'Find people to attend events with',
      'Find a study partner'
    ]
  },
  {
    id: 's12',
    name: 'Zoya Merchant',
    avatarSeed: 9,
    emoji: '☕',
    college: 'Jai Hind College',
    course: 'BSc Data Science',
    year: '3rd Year',
    bio: 'Kaggle on weekends. Happy to explain regression to anyone who brings coffee.',
    interests: ['AI & Machine Learning', 'Technology', 'Psychology', 'Sustainability'],
    hobbies: ['Coding side projects', 'Reading', 'Running'],
    skills: ['Python', 'Data analysis', 'Research', 'Teaching / tutoring'],
    careerInterests: ['Data science', 'Academia & research', 'Startups'],
    goals: ['Crack placements', 'Build a portfolio', 'Learn a new skill'],
    personality: ['Analytical', 'Calm', 'Independent'],
    activities: ['Hackathons', 'Library grind', 'Morning runs'],
    lookingFor: ['Find a study partner', 'Work on projects', 'Networking']
  },
  {
    id: 's13',
    name: 'Neel Kapadia',
    avatarSeed: 0,
    emoji: '🪁',
    college: "St. Xavier's College",
    course: 'BA Economics',
    year: '3rd Year',
    bio: 'Model UN regular. Trying to start a policy reading circle across colleges.',
    interests: ['Public Speaking', 'Debate', 'Sustainability', 'Literature'],
    hobbies: ['Reading', 'Writing', 'Chess'],
    skills: ['Research', 'Public speaking', 'Copywriting'],
    careerInterests: ['Civil services', 'Consulting', 'Academia & research'],
    goals: ['Grow my network', 'Publish my work', 'Win a case competition'],
    personality: ['Analytical', 'Ambivert', 'Organised'],
    activities: ['Case competitions', 'Volunteering', 'Cafe study sessions'],
    lookingFor: ['Networking', 'Find teammates', 'Work on projects']
  },
  {
    id: 's14',
    name: 'Riya Sethi',
    avatarSeed: 11,
    emoji: '🧗',
    college: 'Mithibai College',
    course: 'BMS',
    year: '2nd Year',
    bio: 'Weekend trekker, weekday marketer. Sahyadris every second Saturday.',
    interests: ['Travel', 'Marketing', 'Sustainability', 'Photography'],
    hobbies: ['Trekking', 'Photography', 'Cooking'],
    skills: ['Social media', 'Copywriting', 'Event management'],
    careerInterests: ['Marketing & brand', 'Startups'],
    goals: ['Get fitter', 'Build a portfolio', 'Grow my network'],
    personality: ['High energy', 'Spontaneous', 'Empathetic'],
    activities: ['Long walks & city exploring', 'Photowalks', 'Volunteering'],
    lookingFor: [
      'Find people to attend events with',
      'Explore new hobbies',
      'Make new friends'
    ]
  },
  {
    id: 's15',
    name: 'Aditya Ghosh',
    avatarSeed: 13,
    emoji: '🚀',
    college: 'NM College',
    course: 'BAF',
    year: '3rd Year',
    bio: 'Second attempt at a startup. First one taught me more than the syllabus did.',
    interests: ['Entrepreneurship', 'Finance & Markets', 'Technology', 'Marketing'],
    hobbies: ['Coding side projects', 'Podcasts', 'Gym'],
    skills: ['Financial modelling', 'Product thinking', 'Sales'],
    careerInterests: ['Startups', 'Investment banking', 'Product management'],
    goals: ['Build a startup', 'Grow my network', 'Land an internship'],
    personality: ['Competitive', 'Extroverted', 'Independent'],
    activities: ['Startup / E-Cell events', 'Case competitions', 'Gym sessions'],
    lookingFor: [
      'Entrepreneurship / startup connections',
      'Find teammates',
      'Networking'
    ],
    premium: true
  },
  {
    id: 's16',
    name: 'Nikita Shah',
    avatarSeed: 15,
    emoji: '🍜',
    college: 'KC College',
    course: 'BA Psychology',
    year: '1st Year',
    bio: 'Food blog with 40 followers, 38 of them relatives. Will try any new cafe.',
    interests: ['Food', 'Psychology', 'Travel', 'Social Impact'],
    hobbies: ['Cooking', 'Photography', 'Dance'],
    skills: ['Social media', 'Photography', 'Copywriting'],
    careerInterests: ['Media & journalism', 'Social sector'],
    goals: ['Learn a new skill', 'Build a portfolio', 'Grow my network'],
    personality: ['Spontaneous', 'Empathetic', 'Extroverted'],
    activities: ['Cafe study sessions', 'Photowalks', 'Open mics'],
    lookingFor: ['Make new friends', 'Explore new hobbies', 'Find people with similar interests']
  },
  {
    id: 's17',
    name: 'Yash Bhandari',
    avatarSeed: 2,
    emoji: '🧠',
    college: 'VJTI Mumbai',
    course: 'BTech Computer Engineering',
    year: '3rd Year',
    bio: 'Two hackathon wins, zero design sense. Actively looking for a designer co-founder.',
    interests: ['Technology', 'AI & Machine Learning', 'Entrepreneurship', 'Gaming'],
    hobbies: ['Coding side projects', 'Chess', 'Gaming'],
    skills: ['Python', 'JavaScript', 'React', 'Data analysis'],
    careerInterests: ['Software engineering', 'Startups', 'Data science'],
    goals: ['Build a startup', 'Crack placements', 'Build a portfolio'],
    personality: ['Analytical', 'Independent', 'Curious'],
    activities: ['Hackathons', 'Startup / E-Cell events', 'Library grind'],
    lookingFor: [
      'Find teammates',
      'Entrepreneurship / startup connections',
      'Work on projects'
    ]
  },
  {
    id: 's18',
    name: 'Priya Menon',
    avatarSeed: 7,
    emoji: '📚',
    college: 'Sydenham College',
    course: 'BCom',
    year: '2nd Year',
    bio: 'Study group organiser. Pomodoro evangelist. Will hold you accountable, kindly.',
    interests: ['Finance & Markets', 'Literature', 'Psychology'],
    hobbies: ['Reading', 'Running', 'Board games'],
    skills: ['Accounting', 'Teaching / tutoring', 'Research'],
    careerInterests: ['Consulting', 'Investment banking'],
    goals: ['Improve my grades', 'Crack placements', 'Land an internship'],
    personality: ['Organised', 'Calm', 'Collaborative'],
    activities: ['Library grind', 'Cafe study sessions', 'Morning runs'],
    lookingFor: ['Find a study partner', 'Make new friends', 'Networking']
  },
  {
    id: 's19',
    name: 'Karan Malhotra',
    avatarSeed: 5,
    emoji: '🎧',
    college: 'IIT Bombay',
    course: 'BTech Mechanical',
    year: '4th Year',
    bio: 'Robotics team lead. Producing lo-fi tracks when the lab is closed.',
    interests: ['Technology', 'Music', 'Gaming', 'Sports'],
    hobbies: ['Guitar', 'Coding side projects', 'Basketball'],
    skills: ['Python', 'Product thinking', 'Research'],
    careerInterests: ['Software engineering', 'Product management'],
    goals: ['Crack placements', 'Build a portfolio', 'Study abroad'],
    personality: ['Curious', 'Independent', 'Calm'],
    activities: ['Hackathons', 'Music jams', 'Football matches'],
    lookingFor: ['Work on projects', 'Networking', 'Explore new hobbies']
  },
  {
    id: 's20',
    name: 'Simran Kaur',
    avatarSeed: 12,
    emoji: '🎤',
    college: "St. Xavier's College",
    course: 'BMM / Mass Media',
    year: '2nd Year',
    bio: 'Open mic every Thursday. Poetry, mostly bad, occasionally not.',
    interests: ['Literature', 'Music', 'Film & Cinema', 'Social Impact'],
    hobbies: ['Writing', 'Singing', 'Theatre'],
    skills: ['Copywriting', 'Public speaking', 'Video editing'],
    careerInterests: ['Media & journalism', 'Marketing & brand'],
    goals: ['Publish my work', 'Organise campus events', 'Build a portfolio'],
    personality: ['Creative', 'Extroverted', 'Empathetic'],
    activities: ['Open mics', 'Film screenings', 'Volunteering'],
    lookingFor: [
      'Find people to attend events with',
      'Find people with similar interests',
      'Make new friends'
    ]
  },
  {
    id: 's21',
    name: 'Farhan Qureshi',
    avatarSeed: 4,
    emoji: '📷',
    college: 'KC College',
    course: 'BSc Computer Science',
    year: '2nd Year',
    bio: 'Street photography and Python. Both are about noticing patterns, I tell myself.',
    interests: ['Photography', 'Technology', 'Travel', 'Film & Cinema'],
    hobbies: ['Photography', 'Coding side projects', 'Trekking'],
    skills: ['Python', 'Photography', 'JavaScript'],
    careerInterests: ['Software engineering', 'Design'],
    goals: ['Build a portfolio', 'Learn a new skill', 'Land an internship'],
    personality: ['Introverted', 'Creative', 'Curious'],
    activities: ['Photowalks', 'Hackathons', 'Long walks & city exploring'],
    lookingFor: [
      'Find people with similar interests',
      'Explore new hobbies',
      'Work on projects'
    ]
  },
  {
    id: 's22',
    name: 'Aisha Contractor',
    avatarSeed: 10,
    emoji: '🌱',
    college: 'Mithibai College',
    course: 'BA Economics',
    year: '1st Year',
    bio: 'Volunteering at a literacy NGO on weekends. Looking for people who want to help.',
    interests: ['Social Impact', 'Sustainability', 'Psychology', 'Literature'],
    hobbies: ['Reading', 'Dance', 'Cooking'],
    skills: ['Teaching / tutoring', 'Event management', 'Research'],
    careerInterests: ['Social sector', 'Civil services'],
    goals: ['Grow my network', 'Organise campus events', 'Learn a new skill'],
    personality: ['Empathetic', 'Collaborative', 'Ambivert'],
    activities: ['Volunteering', 'Cafe study sessions', 'Open mics'],
    lookingFor: ['Work on projects', 'Make new friends', 'Find teammates']
  }
];

export function studentById(id: string): Student | undefined {
  return STUDENTS.find((s) => s.id === id);
}

/** Students seeded as having already sent the demo user a LinkUp request. */
export const SEEDED_INCOMING = ['s4', 's11', 's16'];
